language: node_js
node_js:
  - "10"
before_script:
  - npm install
  - npm install -g firebase-tools
  
script:
 - echo "Deploy!!"
 - ng build --prod

after_success:
  - firebase deploy --project cms-app3 --token $FIREBASE_TOKEN